name: 'Rotate AWS Access Keys'
author: 'Nema Darban <nema.darban@gmail.com>'
description: Github action that rotates the iam user tokens on a schedule
runs:
    using: 'docker'
    image: 'Dockerfile'
branding:
    icon: 'check-circle'
    color: 'blue'