name: validate master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rotate-validate:
    name: rotate validate iam user keys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0

      - name: rotate aws keys
        uses: ajaychinthapalli/github-action-rotate-aws-secrets@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_KEY_VALUE: ${{ secrets.AWS_ACCESS_KEY_VALUE }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          OWNER_REPOSITORY: ${{ github.repository }}

      - name: just echo a failure message
        run: | 
          echo Failed to rotate token for '${{ secrets.validate_username}}' in gihub-action-rotate-aws-secrets!

  rotate-recovery:
    name: rotate recovery iam user keys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0

      - name: rotate aws keys
        uses: ajaychinthapalli/github-action-rotate-aws-secrets@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_KEY_VALUE: ${{ secrets.AWS_ACCESS_KEY_VALUE }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          OWNER_REPOSITORY: ${{ github.repository }}

      - name: just echo a failure message
        run: | 
          echo Failed to rotate token for '${{ secrets.validate_username}}' in gihub-action-rotate-aws-secrets!
